# -*- coding: utf-8 -*-
"""ETL_PYMES.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ct8SKe7OHmzP-mdXTcjCI9SZa7JvAOHK

#Porceso ETL
"""

#Importaremos las librerias que ocuparemos para nuestro proceso de ETL
import pandas as pd
import numpy as np
import ast

"""###Extracción"""

#Importamos nuestra segunda base de datos
PYMES = pd.read_csv('/content/DATOS_COMBINADOS.csv')
PYMES.head(3)

# Convert to datetime and extract year
#PYMES['fecha_alta'] = pd.to_datetime(PYMES['fecha_alta'], format='%Y-%m-%d', errors='coerce') # Use pd.to_datetime to convert the column, handle errors
#PYMES['año'] = PYMES['fecha_alta'].dt.year # Use PYMES instead of df

#Corregiremos los errores ortograficos que esten en la tabla
PYMES_1 = PYMES.rename(columns = {'entidad': 'Estado', 'fecha_alta': 'fecha'})
PYMES_1.head(3)

#Datos estadisticos
PYMES_1.describe()

PYMES_1.count()

PYMES_1.duplicated().sum()

#Como podemos ver hay 118 datos duplicados por lo que se eliminan ya que no se utilizaran
PYMES_1.drop_duplicates(inplace = True)

#Corroboramos si se eliminaron los duplicados
PYMES_1.duplicated().sum()

PYMES_1.count()

PYMES_1.isnull().sum()

PYMES_1.dtypes

#Convertimos los datos ya procesados a un CSV para su uso mas facil
from google.colab import files
PYMES_1.to_csv('PYMES_1.csv', encoding = 'utf-8-sig')
# The file name in files.download should match the file name used in to_csv
files.download('PYMES_1.csv') # Changed 'PYMES_LISTO.csv' to 'PYMES_1.csv'